Repository SPAAM-community/AncientMetagenomeDir, pull requests merged in 2021-11, with the labels that each got.

#627 Add Weyrich 2017 libs
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries.tsv
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries_RAW.tsv
  assets/documentation/libraries/README.md
Labels: Ready for Review

#639 Add Sabin2020.b libs
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: Ready for Review

#641 Add Bos2014 libs
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: Ready for Review

#664 Updated lib for Guellil2020
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: bacterium, Ready for Review, libraries

#669 Wibowo2021-libs
  ancientmetagenome-environmental/libraries/ancientmetagenome-environmental_libraries.tsv
Labels: environmental, Ready for Review

#653 Add Ozga2016 lib info
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries.tsv
Labels: Ready for Review

#648 Add lib info for Borry2020
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries.tsv
Labels: Ready for Review

#628 Add Fotakis2020 calculus libraries
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries.tsv
Labels: Ready for Review

#645 Add Bos2011
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: Ready for Review

#632 Sabin2020 lib
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries.tsv
Labels: Ready for Review

#654 Add Eerkens2018-libs
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: Ready for Review

#657 Add Gelabert2016-libs
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: Ready for Review

#660 Add Rampelli2021b libs
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries.tsv
Labels: Ready for Review

#666 Eisenhoffer2020 libs
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries.tsv
Labels: Ready for Review

#686 Vagene2018_lib
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: do not merge

#642 Farrer2021
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries.tsv
Labels: Ready for Review

#661 Add Maixner2021-libs
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries.tsv
Labels: Ready for Review

#665 Add Hagan2019-libs
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries.tsv
Labels: Ready for Review

#678 Add Kilinc2021-libs
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: singlegenome-hostassociated, bacterium, Ready for Review, libraries

#687 Add Philips2017-libs
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries.tsv
Labels: Ready for Review

#699 Add Rifkin2020-libs
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries.tsv
Labels: Ready for Review

#702 Rifkin2020 environmental samples libs
  ancientmetagenome-environmental/libraries/ancientmetagenome-environmental_libraries.tsv
Labels: Ready for Review

#689 add Keller2019 libs
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: Ready for Review

#713 Haller2021
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: singlegenome-hostassociated, Ready for Review

#715 Spyrou2019 libs
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: Ready for Review
