Repository SPAAM-community/AncientMetagenomeDir, pull requests merged in 2021-12, with the labels that each got.

#743 Add Devault2017
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: singlegenome-hostassociated, Ready for Review

#742 Schuenemann 2013 libs
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: singlegenome-hostassociated, Ready for Review

#729 added lib info for AndradesValtuena2017
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: singlegenome-hostassociated, bacterium, Ready for Review, libraries

#730 add lib info susat2021
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: singlegenome-hostassociated, bacterium, Ready for Review, libraries

#728 Add Dommain 2020 libs
  ancientmetagenome-environmental/libraries/ancientmetagenome-environmental_libraries.tsv
Labels: Ready for Review

#704 Fagernas2021 libs
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries.tsv
Labels: Ready for Review

#685 Add Kazarina2021-libs
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries.tsv
Labels: Ready for Review

#707 Add Wibowo2021 paleofeces - libs
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries.tsv
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: problematic, Ready for Review

#677 DeDios2020
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: Ready for Review

#764 Krause kyora2018b libs
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: Ready for Review

#727 Susat 2020
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: Ready for Review

#720 Spyrou2018 libs
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: Ready for Review

#769 Campos2021 libs
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: Ready for Review

#643 Add Schulte 2021 libs
  ancientmetagenome-environmental/libraries/ancientmetagenome-environmental_libraries.tsv
Labels: Ready for Review

#651 Add Rampelli2021 lib info
  ancientmetagenome-environmental/libraries/ancientmetagenome-environmental_libraries.tsv
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries.tsv
Labels: question, metagenome-hostassociated, environmental, Ready for Review

#777 Yu2020 lib
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: Ready for Review

#716 Add Brelaey 2020 Libs
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries.tsv
  assets/enums/sequencing_center.json
Labels: Ready for Review

#672 add Key2020 libs
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: Ready for Review

#712 Guellil2018-libs2_rereview
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: Ready for Review

#721 Rasmussen2015 libs
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: singlegenome-hostassociated, bacterium, Ready for Review, libraries

#711 Add Lammers2021-libraries
  ancientmetagenome-environmental/libraries/ancientmetagenome-environmental_libraries.tsv
Labels: environmental, Ready for Review

#822 Added Ardelean2020-libs
  ancientmetagenome-environmental/libraries/ancientmetagenome-environmental_libraries.tsv
Labels: environmental, Ready for Review

#821 Add Moguel2021 libs
  ancientmetagenome-environmental/libraries/ancientmetagenome-environmental_libraries.tsv
Labels: environmental, Ready for Review

#819 Added Liang2021-libs
  ancientmetagenome-environmental/libraries/ancientmetagenome-environmental_libraries.tsv
Labels: environmental, Ready for Review

#818 Added Borry2020-libs
  ancientmetagenome-environmental/libraries/ancientmetagenome-environmental_libraries.tsv
Labels: environmental, Ready for Review

#811 Add Slon2017 libs
  ancientmetagenome-environmental/libraries/ancientmetagenome-environmental_libraries.tsv
Labels: environmental, Ready for Review

#815 Adding Neukamm2020-libs metagenomic sequences
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries.tsv
Labels: Ready for Review
