Repository SPAAM-community/AncientMetagenomeDir, pull requests merged in 2022-02, with the labels that each got.

#800 Add Gaffney2020 libs
  ancientmetagenome-environmental/libraries/ancientmetagenome-environmental_libraries.tsv
Labels: Ready for Review

#814 Adding Yoshida2013 libs
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: question, Ready for Review

#762 add Martin2013
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: Ready for Review

#774 Warinner2014 libs
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: Ready for Review

#775 Devault2014
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: Ready for Review

#809 Adding Neukmann 2020 libs - singlegenome hostassociated
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: Ready for Review

#724 Add Philips2020 libs
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: Ready for Review

#754 Add Ferrari2020 libs
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: Ready for Review

#788 Maixner2016 libs
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: Ready for Review

#790 Add Ferrari2018 libs
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries.tsv
Labels: Ready for Review

#766 Kocher2021 samples
  CHANGELOG.md
  ancientsinglegenome-hostassociated/samples/ancientsinglegenome-hostassociated_samples.tsv
Labels: Ready for Review, samples

#793 Add Campana2014 libs
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries.tsv
Labels: Ready for Review

#833 Brealey2020(2021 actual) libs - now with blanks removed
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries.tsv
Labels: Ready for Review

#780 Zhou 2018 libs
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: problematic, Ready for Review

#786 GuzmanSolis2021
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
Labels: problematic, Ready for Review
