Repository SPAAM-community/AncientMetagenomeDir, pull requests merged in 2025-04, with the labels that each got.

#1372 Add RodriguezVarela2024 samples
  CHANGELOG.md
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
  ancientsinglegenome-hostassociated/samples/ancientsinglegenome-hostassociated_samples.tsv
Labels: new-publication

#1373 LlanosLizcano2025
  CHANGELOG.md
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
  ancientsinglegenome-hostassociated/samples/ancientsinglegenome-hostassociated_samples.tsv
Labels: new-publication

#1331 Patrono2022
  CHANGELOG.md
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
  ancientsinglegenome-hostassociated/samples/ancientsinglegenome-hostassociated_samples.tsv
  assets/utility/autofill-wrapper.sh
Labels: new-publication, Ready for Review

#1422 C14Maixner2016
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review, C14 dating

#1423 C14 feldman2016
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review, C14 dating

#1421 C14 Rascovan2019
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review, C14 dating

#1431 C14 DeDios2019
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: C14 dating

#1427 C14: Kerudin2019
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review, C14 dating

#1430 C14: Worobey 2016
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review, C14 dating

#1432 C14 Schuenemann2011
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review, C14 dating

#1433 C14 Duggan2020
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review, C14 dating

#1384 Add Barquera2024
  CHANGELOG.md
  ancientsinglegenome-hostassociated/libraries/ancientsinglegenome-hostassociated_libraries.tsv
  ancientsinglegenome-hostassociated/samples/ancientsinglegenome-hostassociated_samples.tsv
Labels: new-publication, Ready for Review

#1436 C14 Spyrou2016
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review, C14 dating

#1212 Add Velsko 2024
  CHANGELOG.md
  ancientmetagenome-hostassociated/libraries/ancientmetagenome-hostassociated_libraries.tsv
  ancientmetagenome-hostassociated/samples/ancientmetagenome-hostassociated_samples.tsv
Labels: new-publication, Ready for Review

#1370 C14 deDios2020
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: do not merge, C14 dating

#1426 C14: Wagner2014
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review, C14 dating

#1437 C14 Martin2013
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review, C14 dating

#1434 C14 Namouchi2018
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review, C14 dating

#1444 C14 Yoshida2013
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review, C14 dating

#1439 C14 Spyrou2019
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review, C14 dating

#1445 C14 Muhlemann2020
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review, C14 dating

#1440 C14 KrauseKyora2018b
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review, C14 dating

#1456 C14 Pla-Diaz2025
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review

#1458 C14 Eisenhofer2020
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review

#1463 C14 Gelabert2016
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review

#1457 C14: Add Urban2024
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review

#1461 C14: Add Rozwalak 2024
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review

#1470 C14 Sarhan2023
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review, C14 dating

#1472 C14 Rieux2021
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review, C14 dating

#1473 C14: Add Long2023
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review

#1475 C14 Granehall2021
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review

#1467 C14 mendum2014
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review

#1485 C14 Marciniak2016
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review

#1481 C14 Clavel2023
  CHANGELOG.md
  ancientsinglegenome-hostassociated/dates/ancientsinglegenome-hostassociated_dates.tsv
Labels: Ready for Review
